### PR TITLE
Add ApolloCLI/ to .gitignore

### PR DESCRIPTION
**Pull request by joel-perry**

### CODE REVIEW

**Review by designatednerd — APPROVED** [review]
Thanks for PR'ing this before we got a chance to! :)

**Comment by designatednerd** [comment]
(LOL guess who looked at this before seeing @calvincestari's comment on your issue 🤦‍♀️)

**Comment by joel-perry** [comment]
I should have started with the PR, so I guess we're even.

**Comment by calvincestari** [comment]
Thanks for this @joel-perry! We're always appreciative of community contributions.

**Pull request merged**
