### PR TITLE
Updated comment about schema downloading configuration

### PR DESCRIPTION
**Pull request by acoomans**
Fixed:
- name of the generated file
- link to online documentation

### CODE REVIEW

**Comment by acoomans** [comment]
After further inspection, this change is not enough. `ApolloCodegenOptions` also assumes the filename to be `schema.json`:

https://github.com/apollographql/apollo-ios/blob/88ee167f247eedad81114da28311df17e8ad2afc/Sources/ApolloCodegenLib/ApolloCodegenOptions.swift#L133

and so do plenty of other files:

https://github.com/apollographql/apollo-ios/search?p=2&q=schema.json

Instead, it looks like it might be better reverting the change in:

https://github.com/apollographql/apollo-ios/blob/22e20977f486db15c19e20d475c2f83e304ba22b/Sources/ApolloCodegenLib/ApolloSchemaDownloader.swift#L253

What do reviewers think?

**Comment by designatednerd** [comment]
I think this is a misunderstanding, I think this should be pointed at the SDL-downloaded `schema` file (blanking right this second but I think I used `graphqls` instead of `sdl` for that file extension)

**Comment by acoomans** [comment]
Let me offer some context here -- or at least what I remember. I setup graphQL for our app a year ago and we're upgrading because Xcode 13 throw an errors. 

The setup is:

`Codegen` project folder next to our `App` folder (similar to what's recommended in the guide)

`Codegen` deviates from the guide in a few ways. We did this because we didn't want to run the codegen script at every build (it was slow).

A) `Codegen/graphQL` folder contains all our `.graphql` mutations/queries/fragments. So in the "download schema" phase, we're passing that directory to `ApolloSchemaDownloadConfiguration`, and this generates a `schema.json` file in `Codegen/graphQL`.

B) In the "codegen phase", because the path to `schema.json` isn't the standard one, we have to pass it to `ApolloCodegenOptions`. 

Now, we're adopting graphQL 0.49.0 and its (newish) `iOSCodegenTemplate`. I kept the changes I made (downloading whatever schema file in `Codegen/graphQL`) but:

- `ApolloSchemaDownloadConfiguration` when used with `introspection` generates `introspection_response.json` (see https://github.com/apollographql/apollo-ios/blob/22e20977f486db15c19e20d475c2f83e304ba22b/Sources/ApolloCodegenLib/ApolloSchemaDownloader.swift#L253) and `schema.graphqls`
- `ApolloCodegenOptions` expects `schema.json` (see https://github.com/apollographql/apollo-ios/blob/88ee167f247eedad81114da28311df17e8ad2afc/Sources/ApolloCodegenLib/ApolloCodegenOptions.swift#L133)

**Comment by designatednerd** [comment]
Got it, `ApolloCodegenOptions` should now expect `schema.graphqls` is where that disconnect is. (cc @calvincestari)

The JSON being downloaded for introspection is now just an intermediate representation before we transform it to SDL, and the schema file you should hand to the code generation is the SDL file. 

We'll get this all hammered out, thanks for bringing this to our attention!

**Comment by acoomans** [comment]
Thanks for your help @designatednerd!

**Comment by designatednerd** [comment]
Closing this in favor of #9 (cc @acoomans)

**Pull request closed without merging**
